services:
  frontend:
    build:
      context: . # build needs shared folder
      dockerfile: client/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - 3000:3000 # frontend exposes port 3000, bind host port 3000 to that
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

  backend:
    build:
      context: . # build needs shared folder
      dockerfile: server/Dockerfile
    ports:
      - 8080:8080 # client browser makes requests directly to API - requests are not coming from my next app
    depends_on:
      - mongo # backend needs mongoDB
    networks:
      - express-mongo # express communicates with mongoDB
    env_file:
      - server/.env.production.local

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  express-mongo:

volumes:
  mongo_data:
